using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Models;

public class TaskDeliveryDetail
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    [Required]
    public Guid TaskId { get; set; }

    [ForeignKey(nameof(TaskId))]
    public Task? Task { get; set; }

    [Required]
    [MaxLength(100)]
    public string RecipientName { get; set; } = string.Empty;

    [Required]
    [MaxLength(30)]
    public string RecipientContact { get; set; } = string.Empty;

    [Required]
    [MaxLength(500)]
    public string DeliveryAddress { get; set; } = string.Empty;

    [MaxLength(100)]
    public string Area { get; set; } = string.Empty;

    [MaxLength(500)]
    public string PackageDescription { get; set; } = string.Empty;

    /// <summary>
    /// Optional DMS employee id (e.g. DRV-001) for assigning a driver in DMS.
    /// </summary>
    [MaxLength(50)]
    public string? CourierEmployeeId { get; set; }

    /// <summary>
    /// Generated by DMS once the delivery order is created (e.g. WB-2026-000001).
    /// </summary>
    [MaxLength(50)]
    public string? DmsWaybillNo { get; set; }

    public int? DmsOrderId { get; set; }

    /// <summary>
    /// Normalized delivery status from DMS: Pending, For Pickup, In Transit, Delivered, Completed, Failed, Cancelled.
    /// </summary>
    [MaxLength(50)]
    public string? DmsStatus { get; set; }

    /// <summary>
    /// Raw status string from DMS (e.g. "Out for Delivery").
    /// </summary>
    [MaxLength(50)]
    public string? DmsRawStatus { get; set; }

    public DateTime? DmsLastSyncedAt { get; set; }

    [MaxLength(500)]
    public string? DmsFailureReason { get; set; }

    public double? DmsLatitude { get; set; }
    public double? DmsLongitude { get; set; }

    /// <summary>
    /// Synchronization state: Pending, Synced, Failed
    /// </summary>
    [MaxLength(30)]
    public string SyncStatus { get; set; } = "Pending";

    [MaxLength(1000)]
    public string? SyncError { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }
}
